### ISSUE TITLE
docker login

### ISSUE THREAD

**Issue by wwallace** [solanolabs/ci_memes-docker#4]
Shouldn't this:
`sudo docker login -e=$DOCKER_EMAIL -u=$DOCKER_USER -p=$DOCKER_PASSWORD`
Be changed to:
`sudo docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD`
Since: 
 According to the `docker login --help`: the single dash ("-e, -u, -p") switches take a parameter and the double dash switch options (--username=, --email=, --password=)  are used to assign an option value

**Comment by wkj** [comment]
Fixed on master branch.  Thanks for the report.
